name: Run_Bash_Script

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-external-event]
  push:

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bash script
        run: |
          chmod +x run.sh
          ./run.sh ${{ secrets.KAGGLE_U }} ${{ secrets.KAGGLE_K }}

      - name: 'Tar files to maintain permissions'
        run: tar -cvf output.tar ./output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./output.tar

      - name: Trigger orx-builder
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/orxaicom/orx-builder/actions/workflows/Build_And_Publish/dispatches \
            -d '{"ref": "main", "event_type": "trigger-external-event"}'
