name: Run_Bash_Script

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-external-event]
  push:

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bash script
        run: |
          chmod +x run.sh
          ./run.sh ${{ secrets.KAGGLE_U }} ${{ secrets.KAGGLE_K }}

      - name: 'Tar files to maintain permissions'
        run: tar -cvf output.tar ./output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./output.tar

      - name: Trigger orx-builder
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.repos.createDispatchEvent({
              owner: 'orxaicom',
              repo: 'orx-builder',
              event_type: 'Build_And_Publish',
              client_payload: {
                ref: 'main'
              }
            });
            console.log(response.data);
